import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body id="body">
        {children}
        <hr />
        <ul id="nav">
          <h2>Examples</h2>
          <li>
            <Link href="/fetch/">Server: fetching</Link>
          </li>
          <li>
            <Link href="/fetch/parallel/">Server: parallel fetching</Link>
          </li>
        </ul>
      </body>
    </html>
  );
}
